apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  version: v1
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: demo-app
      version: v1
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: docker.io/phiroict/demo:20210705.002
        name: demo-app
        ports:
        - containerPort: 10000